### ISSUE TITLE
Reward Ad not working

### ISSUE THREAD

**Issue by MuhammadHaxeeb** [Snehal-Singh174/AdMobIntegration2Flutter#1]
Pulled your project but the Video ads/ Reward Ads aren’t working. Even after trying to ad the test device id as well. Did you face the same issue as well.? Or any help you can provide? 

Thanks

**Comment by Snehal-Singh174** [comment]
can you share the error you are facing?

**Comment by Snehal-Singh174** [comment]
As my AdMob account require integration of payment that's why they are not allowing to load ad.
Here you can find the reason.
![IMG_20230330_210407](https://user-images.githubusercontent.com/53808476/228889365-be3e6acd-808d-414a-bf09-87d5528158ea.jpg)

**Comment by MuhammadHaxeeb** [comment]
Actually, it was an error from Admob. I tried everything possible but the ads didn't work. When open it again next day. It started working.
